# RAM cho Gradle
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1536m -Dfile.encoding=UTF-8
# RAM cho Kotlin compiler
kotlin.daemon.jvmargs=-Xmx2048m

# Ch?y build song song
org.gradle.parallel=true

# Ch? c?u hình các module c?n thi?t
org.gradle.configureondemand=true

# B?t cache Gradle
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# T?i ?u R class
android.nonTransitiveRClass=true